# Generated by Django 4.0.2 on 2022-09-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('question', models.TextField(verbose_name='質問')),
                ('answer', models.TextField(verbose_name='回答')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.CharField(choices=[('clang', 'C/C++'), ('python', 'Python'), ('jk', 'Kotlin/Java')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
