# Generated by Django 4.0.2 on 2022-09-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techtwitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='recordpost',
            name='category',
            field=models.CharField(choices=[('C/C++', 'C/C++'), ('Python', 'Python'), ('Kotlin/Java', 'Kotlin/Java'), ('その他', 'その他')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
